### ISSUE TITLE
Crash with Gregtech Community Edition

### ISSUE THREAD

**Issue by andrew-diamondj** [Firew0lf/exppipes#23] opened 2020-05-26 16:06 UTC
Minecraft version: 1.12.2 singleplayer
Mods: codechickenlib  3.2.3.358  
	   exppipes-0.2.7a.jar
           gregtech   1.9.1.505 

Created a new world, placed a chest and stockkeeper pipe, put some Stone to it's interface and chosen Filter: Ore Dict. Game crashes

[https://pastebin.com/WCTQqs9Q](https://pastebin.com/WCTQqs9Q)

```[Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
	at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
	at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:331) ~[avj.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:760) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[je.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[je.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more```

**Comment by BrewingCoder** [comment] 2020-05-26 16:16
Which forge version are you using?

**Comment by andrew-diamondj** [comment] 2020-05-26 16:26
Forge 14.23.5.2854

**Comment by BrewingCoder** [comment] 2020-05-26 16:29
I will try to take a look at it this week. FWIW I hate gregtech.  Not because of the level of difficulty, but rather because it changes so much of the world around it to enable that difficulty.  I mean really what kind of 'surfacerock' has a tileentity :/

**Comment by andrew-diamondj** [comment] 2020-05-26 16:33
:) Thanx, will wait for results.
Exponentialistics Pipes is a very good and promising project, a good alternative to Buildcraft in case of processing automation

**Comment by Ihamfp** [comment] 2020-05-26 16:35
I just reproduced the crash, same setup but a different error:
```
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:848) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: Stack can not be invalid!
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:499) ~[OreDictionary.class:?]
	at ihamfp.exppipes.tileentities.pipeconfig.Filters$1$4.doesMatch(Filters.java:97) ~[Filters$1$4.class:?]
	at ihamfp.exppipes.tileentities.pipeconfig.FilterConfig.doesMatch(FilterConfig.java:53) ~[FilterConfig.class:?]
	at ihamfp.exppipes.tileentities.TileEntityStockKeeperPipe.serverUpdate(TileEntityStockKeeperPipe.java:75) ~[TileEntityStockKeeperPipe.class:?]
	at ihamfp.exppipes.tileentities.TileEntityPipe.update(TileEntityPipe.java:43) ~[TileEntityPipe.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2019) ~[World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:643) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:842) ~[MinecraftServer.class:?]
	... 4 more
```
This one will be easy to fix. Was the stone block from gregtech of vanilla ?

**Comment by andrew-diamondj** [comment] 2020-05-26 16:38
I used vanilla stone block. I also had this error log in my crash logs. It is attached to this issue

https://pastebin.com/WCTQqs9Q

**Comment by Ihamfp** [comment] 2020-05-26 17:49
Seems fixed on my side, while I was on the Filters file I added a feature to list what matches for some filters (fluid names, TC aspects, and oredict names, might add more). Will commit and push a test build a bit later.

**Comment by Ihamfp** [comment] 2020-05-26 19:30
Test build [here](https://drive.google.com/file/d/11OzqBeVwQJcEOJAMB6goiD4mraNnUYD3/view?usp=sharing), please report if anything is still crashing. There's a lot of debugging trash in the logs, that's normal (I'll remove it before committing).
(Also pipe disconnection should work more reliably).

**Comment by andrew-diamondj** [comment] 2020-05-26 20:41
Ok, test build works OK. Shall I close the issue?

**Comment by Ihamfp** [comment] 2020-05-26 20:43
I will, on the next commit :p

**Comment by andrew-diamondj** [comment] 2020-05-26 20:48
Thanks!

**Closed as completed** 2020-05-26 20:52 UTC
Labels: crash
